#!/bin/sh
set -eu
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --set=app_password="$APP_DB_PASSWORD" <<'SQL'
CREATE ROLE ertad_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD :'app_password';
REVOKE ALL ON DATABASE ertad FROM PUBLIC;
GRANT CONNECT ON DATABASE ertad TO ertad_app;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
SQL
