// Generated by npm run tokens. Edit design/tokens.json.
// Palette values are ARGB integers; no Flutter runtime dependency.
const webLightTokens = <String, int>{
  'background': 0xFFF8FAFC,
  'surface': 0xFFFFFFFF,
  'elevated': 0xFFF1F5F9,
  'text': 0xFF0F172A,
  'muted': 0xFF475569,
  'border': 0xFF94A3B8,
  'primary': 0xFF0369A1,
  'onPrimary': 0xFFFFFFFF,
  'focus': 0xFF0284C7,
  'success': 0xFF166534,
  'danger': 0xFFB91C1C,
};
const webDarkTokens = <String, int>{
  'background': 0xFF0F172A,
  'surface': 0xFF1E293B,
  'elevated': 0xFF334155,
  'text': 0xFFF8FAFC,
  'muted': 0xFFCBD5E1,
  'border': 0xFF64748B,
  'primary': 0xFF7DD3FC,
  'onPrimary': 0xFF0F172A,
  'focus': 0xFF38BDF8,
  'success': 0xFF86EFAC,
  'danger': 0xFFFCA5A5,
};
const mobileLightTokens = <String, int>{
  'background': 0xFFF8FAFC,
  'surface': 0xFFFFFFFF,
  'elevated': 0xFFEAF0F8,
  'text': 0xFF0F172A,
  'muted': 0xFF475569,
  'border': 0xFF8290A6,
  'primary': 0xFF2563EB,
  'onPrimary': 0xFFFFFFFF,
  'focus': 0xFF2563EB,
  'success': 0xFF166534,
  'danger': 0xFFB91C1C,
};
const mobileDarkTokens = <String, int>{
  'background': 0xFF121212,
  'surface': 0xFF1E1E1E,
  'elevated': 0xFF2C2C2C,
  'text': 0xFFF8FAFC,
  'muted': 0xFFCBD5E1,
  'border': 0xFF858585,
  'primary': 0xFF70B1FF,
  'onPrimary': 0xFF121212,
  'focus': 0xFF70B1FF,
  'success': 0xFF86EFAC,
  'danger': 0xFFFCA5A5,
};
