import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
const tokens = JSON.parse(readFileSync(resolve(root, 'design/tokens.json'), 'utf8'));
let css = '/* Generated by npm run tokens. Edit design/tokens.json. */\n';
let dart = '// Generated by npm run tokens. Edit design/tokens.json.\n// Palette values are ARGB integers; no Flutter runtime dependency.\n';
for (const family of ['web', 'mobile']) {
  for (const mode of ['light', 'dark']) {
    css += `[data-family="${family}"][data-theme="${mode}"] {\n  color-scheme: ${mode};\n`;
    dart += `const ${family}${mode[0].toUpperCase() + mode.slice(1)}Tokens = <String, int>{\n`;
    for (const [key, value] of Object.entries(tokens[family][mode])) {
      css += `  --${key}: ${value};\n`;
      dart += `  '${key}': 0xFF${value.slice(1).toUpperCase()},\n`;
    }
    css += '}\n'; dart += '};\n';
  }
}
css += `:root { --radius-control: ${tokens.radius.control}px; --radius-dialog: ${tokens.radius.dialog}px; --radius-mobile-card: ${tokens.radius.mobileCard}px; }\n`;
for (const [name, content] of [['admin/src/tokens.css', css], ['mobile/lib/core/theme/generated_tokens.dart', dart]]) {
  const path = resolve(root, name);
  if (process.argv.includes('--check')) {
    if (readFileSync(path, 'utf8') !== content) throw new Error(`Stale tokens: ${name}. Run npm run tokens.`);
  } else { mkdirSync(dirname(path), { recursive: true }); writeFileSync(path, content); }
}
